// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyPlatform.Data;

#nullable disable

namespace StudyPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250920181651_UnrestrictMaterialTitleLength")]
    partial class UnrestrictMaterialTitleLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaterialSubGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MaterialSubGroupId");

                    b.ToTable("Materials");

                    b.HasDiscriminator<string>("MaterialType").HasValue("Material");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaterialGroupType")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("MaterialSubGroups");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Flashcard", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Flashcard");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.MaterialSubGroup", "MaterialSubGroup")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialSubGroup");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Subject", "Subject")
                        .WithMany("MaterialSubGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Navigation("MaterialSubGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
