// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlatform.Data;

#nullable disable

namespace StudyPlatform.Migrations.SupabaseDb
{
    [DbContext(typeof(SupabaseDbContext))]
    [Migration("20251109101405_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaterialSubGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialSubGroupId");

                    b.ToTable("Materials");

                    b.HasDiscriminator<string>("MaterialType").HasValue("Material");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialGroupType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("MaterialSubGroups");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Flashcard", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Flashcard");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Mindmap", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Mindmap");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.MaterialSubGroup", "MaterialSubGroup")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialSubGroup");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Subject", "Subject")
                        .WithMany("MaterialSubGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Navigation("MaterialSubGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
