// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlatform.Data;

#nullable disable

namespace StudyPlatform.Migrations.SupabaseDb
{
    [DbContext(typeof(SupabaseDbContext))]
    [Migration("20251113105518_LinkAppUserToSubjects")]
    partial class LinkAppUserToSubjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyPlatform.Data.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.ToTable("app_users", "public");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaterialSubGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialSubGroupId");

                    b.ToTable("Materials", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialGroupType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("MaterialSubGroups");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.QuizQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuizQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuizQuestionAnswers");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Subject")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.SupabaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("users", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Flashcard", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Flashcards", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Mindmap", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasIndex("UserId");

                    b.ToTable("Mindmaps", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Quiz", b =>
                {
                    b.HasBaseType("StudyPlatform.Data.Models.Material");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.AppUser", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.SupabaseUser", "AuthUser")
                        .WithOne()
                        .HasForeignKey("StudyPlatform.Data.Models.AppUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Material", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.MaterialSubGroup", "MaterialSubGroup")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialSubGroup");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Subject", "Subject")
                        .WithMany("MaterialSubGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.QuizQuestion", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.QuizQuestionAnswer", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.AppUser", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Flashcard", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("StudyPlatform.Data.Models.Flashcard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Mindmap", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("StudyPlatform.Data.Models.Mindmap", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Quiz", b =>
                {
                    b.HasOne("StudyPlatform.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("StudyPlatform.Data.Models.Quiz", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.AppUser", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.MaterialSubGroup", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.QuizQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Subject", b =>
                {
                    b.Navigation("MaterialSubGroups");
                });

            modelBuilder.Entity("StudyPlatform.Data.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
